version: '2'
services: 
  nginx-certs:
    image: busybox
    container_name: nginx-certs
    restart: always
    volumes:
      - /etc/nginx/certs
    command: /bin/sh
  nginx-proxy-alpine:
      image: tokyohomesoc/nginx-proxy-alpine
      container_name: nginx-proxy-alpine
      restart: always
      hostname: nginx-proxy-alpine
      ports:
      -  "80:80"
      - "443:443"
      volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      volumes_from: 
      - nginx-certs:ro
  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from: 
      - nginx-proxy-alpine
    command: ["-notify-sighup", "nginx-proxy-alpine", "-watch", "-wait", "5s:30s", "/app/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: docker-gen
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
    - nginx-certs:rw
    - nginx-proxy-alpine:rw